swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /robotcode:
    get:
      operationId: robotcode.read
      tags:
        - robotcode
      summary: The python script data structure for server
      description: Read all entries in db
      responses:
        200:
          description: Successfully read all entries

    post:
      operationId: robotcode.create
      tags:
        - robotcode
      summary: Create a robot and add it to the robot list
      description: Create a new robot in the robot list
      parameters:
        - name: robotcode
          in: body
          description: Robot code to create
          required: True
          schema:
            type: object
            properties:
              robot:
                type: string
                description: Robot id/name
              code:
                type: string
                description: code to execute on robot
      responses:
        201:
          description: Successfully created robot in list


  /robotcode/{robot_id}:
    get:
      operationId: robotcode.read_one
      tags:
        - robotcode
      summary: Read code from the robot list
      description: Read code from the robot list
      parameters:
        - name: robot_id
          in: path
          description: Robot name of the code to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read code from robot list operation
          schema:
            properties:
              robot:
                type: string
              code:
                type: string

    put:
      operationId: robotcode.update
      tags:
        - robotcode
      summary: Update code in the robot list
      description: Update code in the code list
      parameters:
        - name: robot_id
          in: path
          description: robot name of the robot to update in the list
          type: integer
          required: True
        - name: robotcode
          in: body
          schema:
            type: object
            properties:
              robot:
                type: string
              code:
                type: string
      responses:
        200:
          description: Successfully updated code in robot list
